# Generated by Django 5.2.7 on 2025-10-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaaz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('motor', 'Motor'), ('pump', 'Pump'), ('valve', 'Valve'), ('turbine', 'Turbine'), ('heat_exchanger', 'Heat Exchanger'), ('compressor', 'Compressor'), ('fan', 'Fan'), ('gearbox', 'Gearbox'), ('bearing', 'Bearing'), ('other', 'Other')], max_length=20)),
                ('plant_location', models.CharField(choices=[('unit_a', 'Unit A'), ('unit_b', 'Unit B'), ('unit_c', 'Unit C'), ('unit_t', 'Unit T'), ('hx5_area', 'HX5 Area'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
